package image;

public enum Image {
	GLOBO_ROJO, GLOBO_AZUL, GLOBO_VERDE, MOAB, JUGADOR, PREMIO_TIEMPO, PREMIO_VIDA, PROYECTIL, VIENTO, BACKGROUND, ICON,
	PREMIO_DMG, LVL_CLEAR, NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9;
}
